smartrasp_server/meetingScreen/urls.py
from django.urls import path

from . import views

app_name = 'meetingScreen'
urlpatterns = [
    path('', views.index_page, name='index'),
    path('table', views.table_current_week, name='table_cur_week'),
    path('table/<int:week_number>', views.table_page, name='table'),
    path('new_student', views.create_new_student, name='new_student'),
    path('new_teacher', views.create_new_teacher, name='new_teacher'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('new_filter', views.create_new_filter, name='new_filter'),
    path('settings', views.settings_page, name='settings_page'),
    path('change_password_action', views.change_password_action,
         name='change_password_action'),
]

smartrasp_server/smartrasp_server/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('meetingScreen.urls')),
    path('admin/', admin.site.urls),
]

smartrasp_server/meetingScreen/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.exceptions import ValidationError
# django's settings needs for use Django's Schedule model as a foreign key
from django.conf import settings

import datetime


# Create your models here.


class Teacher(models.Model):
    full_name = models.CharField(max_length=150, unique=True)
    last_link = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.full_name


class Subject(models.Model):
    full_name = models.CharField(max_length=300, unique=True)
    short_name = models.CharField(max_length=100)

    def __str__(self):
        return self.short_name


class Group(models.Model):
    name = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.name


class Lesson(models.Model):
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE,
                                null=True, blank=True)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    date = models.DateField(null=False, blank=False)
    lesson_number = models.PositiveIntegerField(
        "Lesson's number in the day (from 1 to 7)",
        validators=[MinValueValidator(1), MaxValueValidator(8)])
    type = models.CharField(max_length=10, null=False, blank=False,
                            default='ПР')

    class Meta:
        unique_together = (('teacher', 'subject', 'group', 'date',
                            'lesson_number', 'type'),)


class Schedule(models.Model):
    django_user_ref = models.OneToOneField(settings.AUTH_USER_MODEL,
                                           on_delete=models.CASCADE,
                                           null=False, blank=False)
    main_group = models.ForeignKey(Group, on_delete=models.CASCADE,
                                   null=True, blank=True)
    main_teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE,
                                     null=True, blank=True)
    STUDENT = 0
    TEACHER = 1
    schedule_type_choices = (
        (STUDENT, 'Student'),
        (TEACHER, 'Teacher'),
    )
    schedule_type = models.IntegerField(default=0,
                                        choices=schedule_type_choices)

    def __str__(self):
        return str(self.id)

    def clean(self):
        """We should check if we adding user with correct fields
        filling. Student must have main group and must not have main
        teacher. Same for the teacher"""
        # Check for correct filling for student
        if self.schedule_type == self.STUDENT:
            if self.main_group is None:
                raise ValidationError('Student must have main group')
            if self.main_teacher is not None:
                raise ValidationError('Student must not have main teacher')
        # Check for correct filling for teacher
        if self.schedule_type == self.TEACHER:
            if self.main_teacher is None:
                raise ValidationError('Teacher must have main teacher')
            if self.main_group is not None:
                raise ValidationError('Teacher must not have main group')


class WeekDay(models.Model):
    day_name_choices = (
        (1, "Monday"),
        (2, "Tuesday"),
        (3, "Wednesday"),
        (4, "Thursday"),
        (5, "Friday"),
        (6, "Saturday"),
    )
    day_name = models.IntegerField(default=1, choices=day_name_choices,
                                   null=False, blank=False, unique=True)


class FilterInterface:
    """Using this interface you MUST create filter values dictionary.
    Filter values dict have next format: {"lessons_field": filter_value}
    """

    def filter_hide(self, lessons_set):
        """Returns lessons set without hide lessons"""
        filter_values = self.get_filter_values()
        # You must return empty array, showing that there is no
        # shadow filtered Lesson objects
        return lessons_set.exclude(**filter_values), lessons_set.none()

    def filter_shadow(self, lessons_set):
        """Returns two lessons set, with common and with shadow
        lessons"""
        filter_values = self.get_filter_values()
        shadow_lessons_set = lessons_set.filter(**filter_values)
        common_lessons_set = lessons_set.difference(shadow_lessons_set)
        return common_lessons_set, shadow_lessons_set

    def filter(self, lessons_set):
        if self.type == self.HIDE:
            return self.filter_hide(lessons_set)
        else:
            return self.filter_shadow(lessons_set)


class BaseFilter(FilterInterface, models.Model):
    schedule = models.ForeignKey(Schedule, on_delete=models.CASCADE,
                                 null=False, blank=False)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE,
                                null=False, blank=False)
    HIDE = 0
    SHADOW = 1
    type_choices = (
        (HIDE, "Hide"),
        (SHADOW, "Shadow")
    )
    type = models.IntegerField(default=0, choices=type_choices,
                               null=False, blank=False)

    class Meta:
        abstract = True


class FilterSubjectName(BaseFilter):
    """Simple filter based on subject name"""

    def get_filter_values(self):
        filter_values = {
            'subject': self.subject
        }
        return filter_values

smartrasp_server/meetingScreen/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.models import User as Django_User
from django.contrib.auth import authenticate, login, logout

from .week_handler import get_week_days_with_dates, get_current_week
from .week_handler import get_filtered_week_lessons_for_view

from .models import Schedule, Group, Teacher, FilterSubjectName
from .models import Subject

from random import randint


def index_page(request):
    if request.user.is_authenticated:
        cur_week = get_current_week()
        return HttpResponseRedirect(reverse('meetingScreen:table',
                                            args=(cur_week,)))
    context = {
        "groups_list": Group.objects.all(),
        "teachers_list": Teacher.objects.all(),
        "random_int": randint(1, 999999),
    }
    return render(request, 'meetingScreen/index.html', context)


def table_page(request, week_number):
    if week_number < 1:
        week_number = 1
    week_number = week_number - 1
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('meetingScreen:index'))
    user = Schedule.objects.get(django_user_ref=request.user)
    filtered_week_lessons_with_times = get_filtered_week_lessons_for_view(
        user, week_number)
    print(filtered_week_lessons_with_times)
    context = {
        'filtered_week_lessons_with_time': filtered_week_lessons_with_times,
        'week_days_and_dates': get_week_days_with_dates(week_number),
        'week_number': week_number,
        'profile': Schedule.objects.get(django_user_ref=request.user),
        'random_int': randint(1, 999999),
    }
    return render(request, 'meetingScreen/table.html', context)


def table_current_week(request):
    cur_week = get_current_week()
    return HttpResponseRedirect(reverse('meetingScreen:table',
                                        args=(cur_week,)))


def settings_page(request):
    user = request.user
    if not user.is_authenticated:
        return HttpResponseRedirect(reverse('meetingScreen:index'))
    context = {
        'profile': Schedule.objects.get(django_user_ref=request.user),
        'random_int': randint(1, 999999),
    }
    return render(request, 'meetingScreen/settings.html', context)


def change_password_action(request):
    current_week = get_current_week()
    return HttpResponseRedirect(reverse('meetingScreen:table',
                                        args=(current_week,)))


def create_and_return_new_django_user():
    new_django_user = Django_User.objects.create_user("new_user", "", "")
    new_django_user.username = new_django_user.id
    new_django_user.save()
    return new_django_user


def create_new_student(request):
    schedule_type = Schedule.STUDENT
    main_group = get_object_or_404(Group, name=request.POST['group'])
    new_django_user = create_and_return_new_django_user()
    new_user = Schedule(schedule_type=schedule_type,
                        main_group=main_group,
                        django_user_ref=new_django_user)
    new_user.save()
    login(request, new_django_user)
    cur_week = get_current_week()
    return HttpResponseRedirect(reverse('meetingScreen:table',
                                        args=(cur_week,)))


def create_new_teacher(request):
    schedule_type = Schedule.TEACHER
    main_teacher = get_object_or_404(Teacher, full_name=request.POST['teacher'])
    new_django_user = create_and_return_new_django_user()
    new_user = Schedule(schedule_type=schedule_type,
                        main_teacher=main_teacher,
                        django_user_ref=new_django_user)
    new_user.save()
    login(request, new_django_user)
    cur_week = get_current_week()
    return HttpResponseRedirect(reverse('meetingScreen:table',
                                        args=(cur_week,)))


def create_new_filter(request):
    schedule = get_object_or_404(Schedule, django_user_ref=request.user)
    subject_name = request.POST['subject']
    subject = get_object_or_404(Subject, full_name=subject_name)
    new_filter = FilterSubjectName(schedule=schedule, subject=subject)
    new_filter.save()
    next_page = request.POST.get('next', '/')
    return HttpResponseRedirect(next_page)


def login_view(request):
    username = str(request.POST['rasp_id'])
    password = request.POST['password']

    user = authenticate(request, username=username, password=password)

    if user is not None:
        login(request, user)
        cur_week = get_current_week()

        return HttpResponseRedirect(reverse('meetingScreen:table',
                                            args=(cur_week,)))
    else:
        return HttpResponseRedirect(reverse('meetingScreen:index'))


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('meetingScreen:index'))

smartrasp_server/meetingScreen/templates/meetingScreen/index.html
<!DOCTYPE html>
<!-- file:///home/max/Projects/smartrasp-tpu/index.html -->
<html lang="ru">
<head>
  <meta charset="utf-8">
  <title>SmartRaspTPU - умное расписание ТПУ</title>
  <!-- Bootstrap -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- JQuery -->
  {% load static %}
  <script type="text/javascript" src="{% static 'meetingScreen/jquery-3.6.0.js' %}"></script>
  <script type="text/javascript" src="{% static 'meetingScreen/my_script.js' %}?rand={{ random_int }}"></script>
  <!-- Slides -->
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
  <!-- Site stylesheet -->
  <link rel="stylesheet" type="text/css" href="{% static 'meetingScreen/style.css'%}?rand={{ random_int }}">
</head>
<body>
  <div>
    <div class="container align-items-center">
      <h1 class="greetings">Привет! Я - умное расписание ТПУ.<br>Я помогу составить <strong>твоё</strong> расписание и проще ориентироваться в учебном процессе.</h1>
      <h2>Какое расписание тебе нужно?</h2>
      <!--cards-->
      <div class="row">
        <div class="col-md-4 col-sm-12">
          <div class="card text-center rounded-corners">
            <div class="card-body">
              <h5 class="card-title">Для студентов</h5>
              <p class="card-text">Расписание учебной группы</p>
              <form action="{% url 'meetingScreen:new_student' %}" method="post">
              {% csrf_token %}
                {{ form }}
              <div class="row justify-content-md-center">
              <div class="col-lg-8 col-md-12 group-choice">
                <select class="js-example-basic-single" id="mySelect2" name="group">
                  {% for group in groups_list %}
                  <option>{{group.name}}</option>
                  {% endfor %}
                </select>
              </div>
              </div>
              <button type="submit" class="btn btn-primary rounded-corners">Открыть расписание</button>
              </form>
            </div>
          </div>
        </div>
        <div class="col-md-4 col-sm-12">
          <div class="card text-center rounded-corners">
            <div class="card-body">
              <h5 class="card-title">Для преподавателей</h5>
              <p class="card-text">Расписание по имени преподавателя</p>
              <form action="{% url 'meetingScreen:new_teacher' %}" method="post">
              {% csrf_token %}
              <div class="row justify-content-md-center">
              <div class="col-lg-8 col-md-12 group-choice">
                <select class="js-example-basic-single" id="mySelect3" name="teacher">
                {% for teacher in teachers_list %}
                <option>{{teacher.full_name}}</option>
                {% endfor %}
                </select>
              </div>
              </div>
              <button type="submit" class="btn btn-primary rounded-corners">Открыть расписание</button>
              </form>
            </div>
          </div>
        </div>
        <div class="col-md-4 col-sm-12">
          <div class="card text-center rounded-corners h-100">
            <div class="card-body">
              <h5 class="card-title">Я уже заходил на сайт ранее</h5>
              <p class="card-text">И хочу перенести своё расписание с другого устройства</p>
              <form action="{% url 'meetingScreen:login' %}" method="post">
              {% csrf_token %}
              Логин: <input type="" name="rasp_id" class="rasp-id"><br>
              Пароль: <input type="password" name="password" class="rasp-id"><br>
              <button type="submit" class="btn btn-primary rounded-corners">Открыть расписание</button>
              </form>
            </div>
          </div>
        </div>
      </div>
  </div>
  </div>
</body>
</html>

smartrasp_server/meetingScreen/templates/meetingScreen/settings.html
<!DOCTYPE html>
<!-- file:///home/max/Projects/smartrasp-tpu/table.html -->
<html>
<head>
  <meta charset="utf-8">
  <title>SmartRaspTPU - умное расписание ТПУ</title>
  {% load static %}
  <!-- Bootstrap -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Site stylesheet -->
  <link rel="stylesheet" type="text/css" href="{% static 'meetingScreen/style.css' %}?rand={{random_int}}">
</head>
<body>
  <div class="container align-items-center">
    <div class="row table-view-header">
      <div class="col-4 user-dropdown">
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle rounded-corners" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
            Пользователь: {{request.user.username}}
          </button>
          <ul class="dropdown-menu rounded-corners-light" aria-labelledby="dropdownMenuButton1">
            <li><a class="dropdown-item" href="{% url 'meetingScreen:settings_page'%}">Настройки</a></li>
            <li><a class="dropdown-item" href="{% url 'meetingScreen:logout' %}">Выйти</a></li>
          </ul>
        </div>
      </div>
      <div class="col-lg-4 d-none d-lg-block group-name">Настройки</div>
      <div class="col-lg-4 col-sm-12 col-md-8 group-name text-center text-md-end"><a href="{% url 'meetingScreen:table_cur_week' %}">Расписание</a></div>
    </div>
    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-lg-4 col-md-12">
        <div class="card text-center rounded-corners h-100">
          <div class="card-body">
            <h3>Сменить пароль</h3>
            <form action="{% url 'meetingScreen:change_password_action' %}" method="post">
              {% csrf_token %}
              {{ form }}
              <h5>Старый пароль</h5>
              <input type="password" class="rasp-id" name="old_password">
              <h5><br/>Новый пароль</h5>
              <input type="password" class="rasp-id" name="new_password"><br/>
              <button type="submit" class="btn btn-primary rounded-corners">Сменить пароль</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

smartrasp_server/meetingScreen/templates/meetingScreen/table.html
<!DOCTYPE html>
<!-- file:///home/max/Projects/smartrasp-tpu/table.html -->
<html>
<head>
  <meta charset="utf-8">
  <title>SmartRaspTPU - умное расписание ТПУ</title>
  {% load static %}
  <!-- Bootstrap -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- calendar -->
  <link rel="stylesheet" href="{% static 'meetingScreen/simple-calendar.css' %}">
  <script type="text/javascript" src="{% static 'meetingScreen/jquery-3.6.0.js' %}"></script>
  <script src="{% static 'meetingScreen/jquery.simple-calendar.js' %}"></script>
  <!-- Slides -->
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
  <!-- javascript -->
  <script src="{% static 'meetingScreen/myCalendarScript.js' %}?rand={{random_int}}"></script>
  <script src="{% static 'meetingScreen/table_script.js' %}"></script>
  <!-- Site stylesheet -->
  <link rel="stylesheet" type="text/css" href="{% static 'meetingScreen/style.css' %}?rand={{random_int}}">
</head>
<body>
  <div class="container align-items-center">
    <div class="row table-view-header">
      <div class="col-md-4 user-dropdown">
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle rounded-corners" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
            Пользователь: {{profile.id}}
          </button>
          <ul class="dropdown-menu rounded-corners-light" aria-labelledby="dropdownMenuButton1">
            <li><a class="dropdown-item" href="{% url 'meetingScreen:settings_page'%}">Настройки</a></li>
            <li><a class="dropdown-item" href="{% url 'meetingScreen:logout' %}">Выйти</a></li>
          </ul>
        </div>
      </div>
      <div class="col-md-4 group-name">Расписание группы {{profile.main_group}}</div>
      <div class="col-md-4"></div>
    </div>
    <div class="row table-header align-items-center">
          <div class="col-md-4"><a href="{% url 'meetingScreen:table' week_number %}" class="btn btn-primary rounded-corners">Предыдущая неделя</a></div>
          <div class="col-md-4">
            <div class="dropdown">
              Неделя {{week_number|add:'1'}}
              <button class="calendar-button rounded-corners text-center" type="button" id="dropdownMenyButton2"  data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar" viewBox="0 0 16 16">
              <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z"/>
              </svg>
              </button>
              <div class="dropdown-menu p-2 rounded-corners" style="max-width: 400px;" aria-labelledby="dropdownMenyButton2">
                <div id="calendar_container" class="calendar_container">
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-4"><a href="{% url 'meetingScreen:table' week_number|add:'2' %}" class="btn btn-primary rounded-corners">Следующая неделя</a></div>
    </div>
    <!-- Schedule table -->
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">Время</th>
          {% for day, day_date in week_days_and_dates %}
          <th scope="col" class="week-day">{{day_date}}<br>{{day}}</th>
          {% endfor %}
        </tr>
      </thead>
      <tbody>
          {% for time, common, shadow in filtered_week_lessons_with_time %}
          <tr>
            <th scope="row">{{ time |safe }}</th>
            {% for lessons in common %}
              <td>
                <div class="dropdown">
                  {% for lesson in lessons %}
                  <span class="lesson">
                  <span class="lesson-name">{{lesson.subject.full_name}}</span>
                  </span>
                  <br/>
                  <b class="lesson-teacher">{{ lesson.teacher.full_name }}<br/></b>
                  (<b class="lesson-type">{{ lesson.type }}</b>)
                  <br/>
                  <button class="filter-button rounded-corners text-center">
                    <a href="#filter_lesson_select" class="filter-button">
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-funnel" viewBox="0 0 16 16">
                        <path d="M1.5 1.5A.5.5 0 0 1 2 1h12a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-.128.334L10 8.692V13.5a.5.5 0 0 1-.342.474l-3 1A.5.5 0 0 1 6 14.5V8.692L1.628 3.834A.5.5 0 0 1 1.5 3.5v-2zm1 .5v1.308l4.372 4.858A.5.5 0 0 1 7 8.5v5.306l2-.666V8.5a.5.5 0 0 1 .128-.334L13.5 3.308V2h-11z"/>
                      </svg>
                    </a>
                  </button><hr>
                  {% endfor %}
                </div>
              </td>
            {% endfor %}
          </tr>
          {% endfor %}
      </tbody>
    </table>
    <!-- FILTERS -->
    <hr>
    <div class="row">
      <h1>Добавить фильтр предметов</h1>
      <div class="col-md-4 col-sm-12">
        <div class="card text-center rounded-corners">
          <div class="card-body">
            <h5 class="card-title">По названию предмета</h5>
            <p class="card-text">Все пары по этому предмету будут скрыты</p>
            <form action="{% url 'meetingScreen:new_filter' %}" method="post">
              {% csrf_token %}
              {{ form }}
              <input type="hidden" name="next" value="{{ request.path }}">
              <select class="js-example-basic-single" id="filter_lesson_select" name="subject">

              </select>
              <br>
              <button type="submit" class="btn btn-primary rounded-corners">Добавить фильтр</button>
            </form>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-sm-12">
        <div class="card text-center rounded-corners">
          <div class="card-body">
            <h5 class="card-title">На день недели</h5>
            <p class="card-text">В разработке...</p>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-sm-12">
        <div class="card text-center rounded-corners">
          <div class="card-body">
            <h5 class="card-title">На конкретную дату</h5>
            <p class="card-text">В разработке...</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
</html>